### ISSUE TITLE
octree.cpp won't compile.

### ISSUE THREAD

**Issue by exavi** [aewallin/dualcontouring#1]
There is a mess with opening & closing braces. Can't remember which ones I changed but after changing these it compiled and works fine.

At the moment it crashes if it isn't started with the right number of arguments too, I am happy to push my changes if you want.

**Comment by aewallin** [comment]
I think it compiled for my on Ubuntu 13.04, I can check later.
yes the original user interface is minimal!
If you have a fork with changes, please make a pull request.

**Comment by aewallin** [comment]
I just committed a one-liner fix for the brackets - hope it compiles now for you.

I added a link on the frontpage to the original sourceforge repo, if you want to have a look
